### ISSUE TITLE
Chapter 5

### ISSUE THREAD

**Issue by ivand58** [Josefg/Scientific_FORTH#11]
on page 108, 1st paragraph, there is a single quotation mark, where the quotation should be closed (end of line or at the end of sentence)?

**Comment by Josefg** [comment]
There is not another quotation mark in the book. I think the quotation should be closed at the end of the sentence because the description of the command ends there.

**Comment by Josefg** [comment]
This is again drives the conversation "are we reproducing a book or editing a book?" I'm fine with adding a missing quotation mark, seems like it's in the spirit of the project.

**Comment by ivand58** [comment]
OK, I've started with [*errata*](https://ctan.org/pkg/errata) package; with it is possible to add/remove/change words, and during the *build* one can choose what to be rendered. Is that approach in spirit of the project?
