### ISSUE TITLE
Chapter6

### ISSUE THREAD

**Issue by ivand58** [Josefg/Scientific_FORTH#13]
.

**Comment by Josefg** [comment]
The entirety of your issue is a period. I'm going to need a little more description of the issue ;)

**Comment by ivand58** [comment]
Sorry, i had to remove one fake issue ... but decided to leave the ticket to let you know that I am working on the figures in chapter 6 ...  and I'm going to put there the related issues (if any).

**Comment by ivand58** [comment]
Sorry, i had to remove one fake issue ... but decided to leave the ticket to let you know that I am working on the figures in chapter 6 ...  and I'm going to put there the related issues (if any).

**Comment by ivand58** [comment]
What about the _big list_ in Fig. 6-8 Second order Runge-Kutta - results
 ? the BLOB (numbers) are missing.

**Comment by Josefg** [comment]
Sorry about that. I had planned on going back and adding those numbers when I had a chance. Looks like you beat me to it.

**Comment by ivand58** [comment]
Yep, but additional check is required ...
