### ISSUE TITLE
Issues in chapter 03

### ISSUE THREAD

**Issue by ivand58** [Josefg/Scientific_FORTH#3]
In Chapter 3:
It seems that footnote 20 is missing (referenced in page 59).
Which equation is (1) ?

**Comment by Josefg** [comment]
I'll be copying footnote 20 out of the book. I took a brief look and could not find equation 1, but I'll attempt to address that as well in the tex file.

**Comment by Josefg** [comment]
I would like to apologize for not providing the footnote as I was not aware you were working on Chapter 3. You did a great job and have laid the foundation for me to finish the other diagrams in the book.

The project thanks you for your help. We're one chapter closer!
