### ISSUE TITLE
Issues on Chapter 09

### ISSUE THREAD

**Issue by ivand58** [Josefg/Scientific_FORTH#5]
1. Between Eq. 9 and Eq. 11, there are two unlabeled equations. Any idea which one is (10) ?

**Comment by Josefg** [comment]
We could assume the equation above Eq. 11, det(A) = etc.,  would be Eq. 10. The rest of the section follows the determinant, and thus I think it fits.

It's a little baffling which equations Julian numbered and which ones he did not. I would have had Eq. 9 label Eq. 9 and Eq. 10.

Any further thoughts?

**Comment by Josefg** [comment]
I added the contents of the Scientific Forth Disk. This should reduce typing programs.

**Comment by ivand58** [comment]
I know that the goal of the project is not to make a review of the book, but there is one suspicious reference (p.216) to Eq. 3 (which is I matrix) ... could you take a look?

**Comment by ivand58** [comment]
on page 238 the enumeration of the equations is restarted from 19 (was 21 @ page 223)

**Comment by ivand58** [comment]
on page 226 the FORTH code is referred to EX.3 but  in fact it is in MTOOL and is quite different ... most likely the code in the book is wrong ... So, which one to put in the _.tex_ file?

**Comment by Josefg** [comment]
I think the correct reference should be Eq. 2, as it contains the same variables as 6a, 6b, and 6b'.

I would like to be okay with changing the enumeration. I suggest an unenumerated footnote, noting the change from the original. There are two references at the end of Ch. 9 which would have to be changed to match the new enumeration.

Analysis on page 226: the code at the top of the page is from MTOOL; the NOTES are for EX.3; the third item states }row{ shall be defined below, which it is not; and the content of EX.3 file does not match the print out at the bottom of 226.

Adding the ERRATA file as a page would be within the spirit of the project. Correcting the errata from the file is fine. Adding a project errata page wolud allow the project to inform the reader of the corrections 

What do you think?

**Comment by ivand58** [comment]
> What do you think?

Indeed, we can add additional section (?) for all things that are discovered during the digitalization, but IMHO the "small" typos could be corrected in the text. 
The question that I am asking myself is: what will expect the reader of the book - to have the original one, ore a fixed version. The biggest question for me is about the code from book v.s the code from the "DISK" because there is not doubts if it is buggy or not. The problem with these kind of editions is that if we put too many comments and revisions, this book will begin to look like "The Critique of Pure Reason" :-) So

**Comment by ivand58** [comment]
Could you pls help me with the missing words? 
On page 242, 2nd paragraph 

> We see from Table 2 above that the time computed from the cpu and
coprocessor specifications (422 clocks) is close to the measured time (440 clocks).
The slight difference doubtless comes both from measurement error and from
the fact the timing of CISC chips is not an exact art (for example, there **a ??**
periodic interruptions for dynamic memory refreshment and **f ??** the system
clock).

**Comment by Josefg** [comment]
Table 9-2
a?? = are
f?? = for

**Comment by ivand58** [comment]
Here is the patch:
index e6d34b8..9c22373 100644
--- a/Chapter-09/09-Linear-Algebra.tex
+++ b/Chapter-09/09-Linear-Algebra.tex
@@ -1381,8 +1381,8 @@ in cycles for these basic operations are\sepfootnote{09_16}
 cpu and coprocessor specifications (422 clocks) is close to the
 measured time (440 clocks). The slight difference doubtless
 comes both from measurement error and from the fact the
-timing of CISC chips is not an exact art (for example, there a \underline{??}
-periodic interruptions for dynamic memory refreshment and f \underline{??}
+timing of CISC chips is not an exact art (for example, there are
+periodic interruptions for dynamic memory refreshment and for
 the system clock).
 
 Finally, we confirm that little is to be gained by optimizing out
