### ISSUE TITLE
\TallC{} with single letter 

### ISSUE THREAD

**Issue by ivand58** [Josefg/Scientific_FORTH#6]
In case of single letter in **\TallC**, the rendered letter becomes too small.

A possible work-around is to joint this letter with the next word, for e.g. 
_"A determinant"_ can be presented as \TallC{A\\;determinant} , where **\\;** is the space.

**Comment by Josefg** [comment]
Coo, I shall see how that preforms.

**Comment by Josefg** [comment]
I altered the definition of \TallC{} to split the string used, and thus \TallC{A determinant} works.
